// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  bossEnemyId: __t.u64().name("boss_enemy_id"),
  worldId: __t.u64().name("world_id"),
  headIdx: __t.u32().name("head_idx"),
  currentHp: __t.u32().name("current_hp"),
  maxHp: __t.u32().name("max_hp"),
  regrowAt: __t.u64().name("regrow_at"),
  cauterized: __t.bool(),
});
