// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  charName: __t.string(),
  race: __t.string(),
  attrStr: __t.u32(),
  attrEnd: __t.u32(),
  attrCoord: __t.u32(),
  attrQuick: __t.u32(),
  attrFoc: __t.u32(),
  attrSelf: __t.u32(),
  skillHeavy: __t.u32(),
  skillLight: __t.u32(),
  skillMissile: __t.u32(),
  skillWarMagic: __t.u32(),
  skillLifeMagic: __t.u32(),
  skillItemMagic: __t.u32(),
  skillMeleeDef: __t.u32(),
  skillRun: __t.u32(),
  skillAlchemy: __t.u32(),
};
