// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  worldId: __t.u64().name("world_id"),
  enemyType: __t.string().name("enemy_type"),
  x: __t.f32(),
  y: __t.f32(),
  currentHp: __t.u32().name("current_hp"),
  maxHp: __t.u32().name("max_hp"),
  damage: __t.u32(),
  isBoss: __t.bool().name("is_boss"),
  bossLevel: __t.i32().name("boss_level"),
  mechTimer: __t.u64().name("mech_timer"),
  mechState: __t.string().name("mech_state"),
});
