// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ownerId: __t.identity().name("owner_id"),
  slot: __t.string(),
  itemName: __t.string().name("item_name"),
  icon: __t.string(),
  rarity: __t.u32(),
  stat: __t.string(),
  val: __t.f32(),
  bonusStat: __t.string().name("bonus_stat"),
  bonusVal: __t.f32().name("bonus_val"),
  location: __t.string(),
  groundX: __t.f32().name("ground_x"),
  groundY: __t.f32().name("ground_y"),
  worldId: __t.u64().name("world_id"),
  expiresAtMicros: __t.u64().name("expires_at_micros"),
  itemType: __t.string().name("item_type"),
  paletteGame: __t.string().name("palette_game"),
});
