// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Character = __t.object("Character", {
  id: __t.u64(),
  identity: __t.identity(),
  charName: __t.string(),
  race: __t.string(),
  attrStr: __t.u32(),
  attrEnd: __t.u32(),
  attrCoord: __t.u32(),
  attrQuick: __t.u32(),
  attrFoc: __t.u32(),
  attrSelf: __t.u32(),
  raisedStr: __t.u32(),
  raisedEnd: __t.u32(),
  raisedCoord: __t.u32(),
  raisedQuick: __t.u32(),
  raisedFoc: __t.u32(),
  raisedSelf: __t.u32(),
  skillHeavy: __t.u32(),
  skillLight: __t.u32(),
  skillMissile: __t.u32(),
  skillWarMagic: __t.u32(),
  skillLifeMagic: __t.u32(),
  skillItemMagic: __t.u32(),
  skillMeleeDef: __t.u32(),
  skillRun: __t.u32(),
  skillAlchemy: __t.u32(),
  raisedSkillHeavy: __t.u32(),
  raisedSkillLight: __t.u32(),
  raisedSkillMissile: __t.u32(),
  raisedSkillWarMagic: __t.u32(),
  raisedSkillLifeMagic: __t.u32(),
  raisedSkillItemMagic: __t.u32(),
  raisedSkillMeleeDef: __t.u32(),
  raisedSkillRun: __t.u32(),
  raisedSkillAlchemy: __t.u32(),
  level: __t.u32(),
  totalXp: __t.u64(),
  unspentXp: __t.u64(),
  tokens: __t.u32(),
  earnedCredits: __t.u32(),
  deployed: __t.bool(),
  lastTokenMicros: __t.u64(),
  currentWorldId: __t.u64(),
  homeWorldId: __t.u64(),
  xpHeavy: __t.u64(),
  xpLight: __t.u64(),
  xpMissile: __t.u64(),
  xpWarMagic: __t.u64(),
  xpLifeMagic: __t.u64(),
  xpItemMagic: __t.u64(),
  xpMeleeDef: __t.u64(),
  xpRun: __t.u64(),
  xpAlchemy: __t.u64(),
});
export type Character = __Infer<typeof Character>;

export const CombatSchedule = __t.object("CombatSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CombatSchedule = __Infer<typeof CombatSchedule>;

export const DungeonSpawnSchedule = __t.object("DungeonSpawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  worldId: __t.u64(),
});
export type DungeonSpawnSchedule = __Infer<typeof DungeonSpawnSchedule>;

export const Enemy = __t.object("Enemy", {
  id: __t.u64(),
  worldId: __t.u64(),
  enemyType: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  currentHp: __t.u32(),
  maxHp: __t.u32(),
  damage: __t.u32(),
  isBoss: __t.bool(),
  bossLevel: __t.i32(),
  mechTimer: __t.u64(),
  mechState: __t.string(),
});
export type Enemy = __Infer<typeof Enemy>;

export const EnemyAiSchedule = __t.object("EnemyAiSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type EnemyAiSchedule = __Infer<typeof EnemyAiSchedule>;

export const Item = __t.object("Item", {
  id: __t.u64(),
  ownerId: __t.identity(),
  slot: __t.string(),
  itemName: __t.string(),
  icon: __t.string(),
  rarity: __t.u32(),
  stat: __t.string(),
  val: __t.f32(),
  bonusStat: __t.string(),
  bonusVal: __t.f32(),
  location: __t.string(),
  groundX: __t.f32(),
  groundY: __t.f32(),
  worldId: __t.u64(),
  expiresAtMicros: __t.u64(),
  itemType: __t.string(),
  paletteGame: __t.string(),
});
export type Item = __Infer<typeof Item>;

export const LootLog = __t.object("LootLog", {
  id: __t.u64(),
  identity: __t.identity(),
  icon: __t.string(),
  message: __t.string(),
  rarity: __t.u32(),
  expiresAtMicros: __t.u64(),
});
export type LootLog = __Infer<typeof LootLog>;

export const OlthoiLayerSchedule = __t.object("OlthoiLayerSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  worldId: __t.u64(),
});
export type OlthoiLayerSchedule = __Infer<typeof OlthoiLayerSchedule>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  username: __t.string(),
  online: __t.bool(),
  activeCharacterId: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const PlayerHealth = __t.object("PlayerHealth", {
  identity: __t.identity(),
  currentHp: __t.u32(),
  maxHp: __t.u32(),
});
export type PlayerHealth = __Infer<typeof PlayerHealth>;

export const PlayerPosition = __t.object("PlayerPosition", {
  identity: __t.identity(),
  worldId: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
});
export type PlayerPosition = __Infer<typeof PlayerPosition>;

export const PlayerProgress = __t.object("PlayerProgress", {
  characterId: __t.u64(),
  highestFloorCleared: __t.u32(),
});
export type PlayerProgress = __Infer<typeof PlayerProgress>;

export const PortalCast = __t.object("PortalCast", {
  identity: __t.identity(),
  startedAtMicros: __t.u64(),
  completesAtMicros: __t.u64(),
  tierCap: __t.u32(),
});
export type PortalCast = __Infer<typeof PortalCast>;

export const WaveSpawnSchedule = __t.object("WaveSpawnSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  worldId: __t.u64(),
});
export type WaveSpawnSchedule = __Infer<typeof WaveSpawnSchedule>;

export const World = __t.object("World", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  globalX: __t.f32(),
  globalY: __t.f32(),
  isActive: __t.bool(),
  waveNumber: __t.u32(),
  waveName: __t.string(),
  wavePhase: __t.string(),
  nextWaveAtMicros: __t.u64(),
  bellCooldownUntilMicros: __t.u64(),
  worldType: __t.string(),
  dungeonLevel: __t.u32(),
});
export type World = __Infer<typeof World>;

export const WorldPortal = __t.object("WorldPortal", {
  id: __t.u64(),
  worldId: __t.u64(),
  portalType: __t.string(),
});
export type WorldPortal = __Infer<typeof WorldPortal>;

