// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ownerIdentity: __t.identity().name("owner_identity"),
  globalX: __t.f32().name("global_x"),
  globalY: __t.f32().name("global_y"),
  isActive: __t.bool().name("is_active"),
  waveNumber: __t.u32().name("wave_number"),
  waveName: __t.string().name("wave_name"),
  wavePhase: __t.string().name("wave_phase"),
  nextWaveAtMicros: __t.u64().name("next_wave_at_micros"),
  bellCooldownUntilMicros: __t.u64().name("bell_cooldown_until_micros"),
  worldType: __t.string().name("world_type"),
  dungeonLevel: __t.u32().name("dungeon_level"),
});
