// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CancelPortalCastReducer from "../cancel_portal_cast_reducer";
import CreateCharacterReducer from "../create_character_reducer";
import DeployPlayerReducer from "../deploy_player_reducer";
import EnterDungeonReducer from "../enter_dungeon_reducer";
import EnterPortalReducer from "../enter_portal_reducer";
import EquipItemReducer from "../equip_item_reducer";
import LogoutReducer from "../logout_reducer";
import MovePlayerReducer from "../move_player_reducer";
import MoveToVaultReducer from "../move_to_vault_reducer";
import RespawnPlayerReducer from "../respawn_player_reducer";
import SalvageItemReducer from "../salvage_item_reducer";
import SelectCharacterReducer from "../select_character_reducer";
import SetPlayerNameReducer from "../set_player_name_reducer";
import SpawnTestLootReducer from "../spawn_test_loot_reducer";
import SpendSkillXpReducer from "../spend_skill_xp_reducer";
import SpendTokenReducer from "../spend_token_reducer";
import SpendXpReducer from "../spend_xp_reducer";
import StartPortalCastReducer from "../start_portal_cast_reducer";
import UnequipItemReducer from "../unequip_item_reducer";

export type CancelPortalCastParams = __Infer<typeof CancelPortalCastReducer>;
export type CreateCharacterParams = __Infer<typeof CreateCharacterReducer>;
export type DeployPlayerParams = __Infer<typeof DeployPlayerReducer>;
export type EnterDungeonParams = __Infer<typeof EnterDungeonReducer>;
export type EnterPortalParams = __Infer<typeof EnterPortalReducer>;
export type EquipItemParams = __Infer<typeof EquipItemReducer>;
export type LogoutParams = __Infer<typeof LogoutReducer>;
export type MovePlayerParams = __Infer<typeof MovePlayerReducer>;
export type MoveToVaultParams = __Infer<typeof MoveToVaultReducer>;
export type RespawnPlayerParams = __Infer<typeof RespawnPlayerReducer>;
export type SalvageItemParams = __Infer<typeof SalvageItemReducer>;
export type SelectCharacterParams = __Infer<typeof SelectCharacterReducer>;
export type SetPlayerNameParams = __Infer<typeof SetPlayerNameReducer>;
export type SpawnTestLootParams = __Infer<typeof SpawnTestLootReducer>;
export type SpendSkillXpParams = __Infer<typeof SpendSkillXpReducer>;
export type SpendTokenParams = __Infer<typeof SpendTokenReducer>;
export type SpendXpParams = __Infer<typeof SpendXpReducer>;
export type StartPortalCastParams = __Infer<typeof StartPortalCastReducer>;
export type UnequipItemParams = __Infer<typeof UnequipItemReducer>;

